# Generated by Django 5.2.5 on 2025-08-20 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, help_text='Users enrolled in this course', related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
