# Generated by Django 5.2.5 on 2025-08-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_enrolled_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecurriculumitem',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube video link for this curriculum item', null=True),
        ),
    ]
