# Generated by Django 5.2.5 on 2025-08-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogauthor_blogcategory_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_file',
            field=models.CharField(default=None, help_text="Markdown file name (e.g., 'post-1.md')", max_length=255),
            preserve_default=False,
        ),
    ]
