# Generated by Django 5.2.5 on 2025-08-19 15:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_blogpost_content_blogpost_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content_file',
            field=models.FileField(help_text='Upload markdown file (.md or .markdown)', upload_to='blog/content/', validators=[core.models.validate_markdown_file]),
        ),
    ]
