# Generated by Django 4.2.23 on 2025-08-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_coursecategory_coursereview_course_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='active',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='course',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students_enrolled',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_lessons',
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
